(ns tyrell.site.styles
  "Site-only chrome styles injected into <head> via tyrell.css/ensure-document-styles!.

   Why here, not in tyrell.css (the npm package): tyrell.css ships interaction
   primitive styling — surfaces, text hierarchy, semantic colors. Page chrome like
   inline-code pills in prose belongs to the CONSUMER of tyrell, not the package
   itself. Putting it here keeps tyrell.css consumable by anyone without forcing
   our docs-site choices on them.

   Why not site.css: site.css is generated by Tailwind v4. Appending hand-written
   rules to a generated file is fragile. This namespace owns its own styles,
   gets hot-reloaded by shadow-cljs, and is visible right next to the CLJS code
   that consumes the resulting variables (the (c \"...\") helper, etc.)."
  (:require [tyrell.css :as css]))

;; -----------------------------------------------------------------------------
;; Inline <code> in prose — styles every <code> that's not a hljs code block.
;; Variables live on :root with a .dark override so the page's existing theme
;; toggle (which adds/removes .dark on <html>) drives the swap automatically.
;; -----------------------------------------------------------------------------

(def ^:private inline-code-css
  "
:root {
  --ty-inline-code-bg:     #e2e2e2;
  --ty-inline-code-color:  #2b2b2b;
  --ty-inline-code-border: #cfcfcf;
}

.dark {
  --ty-inline-code-bg:     #2a2a2a;
  --ty-inline-code-color:  #e6e6e6;
  --ty-inline-code-border: #3a3a3a;
}

code:not(.hljs) {
  background:    var(--ty-inline-code-bg);
  color:         var(--ty-inline-code-color);
  border:        1px solid var(--ty-inline-code-border);
  padding:       0.125rem 0.375rem;
  border-radius: 4px;
  font-size:     0.75em;

  /* Wrap behavior — long code strings (e.g. window.tyIcons.register({...}))
     break at character boundaries when they don't fit, instead of overflowing
     the parent's right edge. */
  overflow-wrap: anywhere;
  word-break:    break-word;

  /* When an inline <code> wraps across two lines, render a full pill on each
     fragment (rounded corners + padding + border on both sides) instead of
     slicing the decoration in half. Without this, wrapped code looks chopped:
     the first line ends with a flat right edge, the second starts with a flat
     left edge. */
  -webkit-box-decoration-break: clone;
  box-decoration-break:         clone;
}
")

(defn install!
  "Inject all site-chrome styles into document.head. Idempotent and hot-reloadable
   — calling repeatedly updates the <style> element's content rather than appending
   duplicates. Call from core/init."
  []
  (css/ensure-document-styles! inline-code-css "tyrell-site-inline-code"))
