(ns tyrell.site.styles
  "Site-only chrome styles injected into <head> via tyrell.css/ensure-document-styles!.

   Why here, not in tyrell.css (the npm package): tyrell.css ships interaction
   primitive styling — surfaces, text hierarchy, semantic colors. Page chrome like
   inline-code pills in prose belongs to the CONSUMER of tyrell, not the package
   itself. Putting it here keeps tyrell.css consumable by anyone without forcing
   our docs-site choices on them.

   Why not site.css: site.css is generated by Tailwind v4. Appending hand-written
   rules to a generated file is fragile. This namespace owns its own styles,
   gets hot-reloaded by shadow-cljs, and is visible right next to the CLJS code
   that consumes the resulting variables (the (c \"...\") helper, etc.)."
  (:require [tyrell.css :as css]))

;; Inline <code> in prose — styles every <code> that's not a hljs code block.
;; Variables live on :root with a .dark override so the page's existing theme
;; toggle (which adds/removes .dark on <html>) drives the swap automatically.

(def ^:private inline-code-css
  "
:root {
  --ty-inline-code-bg:     #e2e2e2;
  --ty-inline-code-color:  #2b2b2b;
  --ty-inline-code-border: #cfcfcf;
}

.dark {
  --ty-inline-code-bg:     #2a2a2a;
  --ty-inline-code-color:  #e6e6e6;
  --ty-inline-code-border: #3a3a3a;
}

code:not(.hljs) {
  background:    var(--ty-inline-code-bg);
  color:         var(--ty-inline-code-color);
  border:        1px solid var(--ty-inline-code-border);
  padding:       0.125rem 0.375rem;
  border-radius: 4px;
  font-size:     0.75em;

  /* Wrap behavior — long code strings (e.g. window.tyIcons.register({...}))
     break at character boundaries when they don't fit, instead of overflowing
     the parent's right edge. */
  overflow-wrap: anywhere;
  word-break:    break-word;

  /* When an inline <code> wraps across two lines, render a full pill on each
     fragment (rounded corners + padding + border on both sides) instead of
     slicing the decoration in half. Without this, wrapped code looks chopped:
     the first line ends with a flat right edge, the second starts with a flat
     left edge. */
  -webkit-box-decoration-break: clone;
  box-decoration-break:         clone;
}
")

;; Chrome is PINNED; only page content follows the theme playground.
;;
;; The playground writes its dials as an inline style on <html> (see
;; theming.cljs/apply-seed!), so every flavor-derived colour on the page —
;; including the logo, sidebar and TOC — used to retint as visitors dragged the
;; sliders. Re-declaring the same dials on the chrome subtree stops that: for an
;; inherited custom property, a declaration on the element itself always beats
;; whatever it would have inherited, no matter how specific the ancestor rule is
;; (inline style on <html> included). So the chrome resolves its own seeds and
;; the experiment stays inside <main>.
;;
;; Values mirror theming.cljs/default-seeds (light) and dark-curve-defaults
;; (dark) — keep the three in sync. Hues are theme-invariant, so only the L and
;; chroma curves need a dark block; everything else falls through from light.
;;
;; primary-hue/chroma are the TYRELL IDENTITY color (orange, tuned per-mode —
;; hand-picked off the "Orange" preset in theming.cljs), deliberately NOT the
;; content playground's default (252, violet — picked precisely so a visitor
;; dragging sliders can't land on and be confused with the real brand).
;; success/warning/danger hue + chroma are literal numbers (chroma computed as
;; chrome's-own-chroma × the same ratios core ships: ×1.08 / ×2.22 / ×1.95) +
;; l-factor, pinned explicitly to mirror tyrell-theme.css's own defaults —
;; otherwise the playground's per-flavor chroma and l-factor sliders
;; (theming.cljs) would leak into chrome as INLINE overrides on <html>, the
;; same way any un-pinned dial does — see the maintenance note above.
(def ^:private chrome-pin-css
  "
[data-ty-theme].site-chrome {
  --ty-primary-hue: 38;
  --ty-primary-chroma: 0.15;
  --ty-success-hue: 145;
  --ty-warning-hue: 76;
  --ty-danger-hue: 31;
  --ty-success-chroma: 0.162;
  --ty-warning-chroma: 0.333;
  --ty-danger-chroma: 0.293;
  --ty-success-l-factor: 1;
  --ty-warning-l-factor: 1.3;
  --ty-danger-l-factor: 1.01;
  --ty-l-strong: 0.38;
  --ty-l-bold: 0.46;
  --ty-l-base: 0.54;
  --ty-l-soft: 0.72;
  --ty-l-faint: 0.88;
  --ty-c-strong-mult: 0.77;
  --ty-c-bold-mult: 1;
  --ty-c-base-mult: 0.92;
  --ty-c-soft-mult: 0.77;
  --ty-c-faint-mult: 0.46;

  /* Content lifts this to 0.16 so its solid fills read cleanly; chrome keeps
     the library identity value so header/sidebar fills are untouched. */
  --ty-solid-l: 0;
}

.dark [data-ty-theme].site-chrome,
[data-theme=\"dark\"] [data-ty-theme].site-chrome {
  --ty-primary-hue: 42;
  --ty-primary-chroma: 0.16;
  --ty-primary-l-factor: 1.1;
  --ty-success-chroma: 0.173;
  --ty-warning-chroma: 0.355;
  --ty-danger-chroma: 0.312;
  --ty-l-strong: 0.72;
  --ty-l-bold: 0.66;
  --ty-l-base: 0.62;
  --ty-l-soft: 0.46;
  --ty-l-faint: 0.30;
  --ty-c-faint-mult: 0.50;
  --ty-solid-l: -0.2;
}
")

(defn install!
  "Inject all site-chrome styles into document.head. Idempotent and hot-reloadable
   — calling repeatedly updates the <style> element's content rather than appending
   duplicates. Call from core/init."
  []
  (css/ensure-document-styles! inline-code-css "tyrell-site-inline-code")
  (css/ensure-document-styles! chrome-pin-css "tyrell-site-chrome-pin"))
