(ns tyrell.site.versions
  "Single source of truth for version strings displayed in the docs site.

   These values are regenerated by `clj -T:build regenerate-versions` from
   `packages/cljs/build.clj` (Clojars) and `packages/core/package.json` (npm)
   before each release build, so the install card always shows what's actually
   published. For dev (`npm run dev:site`) the committed defaults are used.")

(def TYRELL_VERSION "1.0.0-RC12")
(def TYRELL_COMPONENTS_VERSION "1.0.0-TC39")
