/**
 * TyCheckbox Web Component — "just the box" primitive: renders only the
 * checkbox visual + state. Label, required asterisk and error display are the
 * consumer's responsibility — wrap in a `<label>` for click delegation.
 */

import type { Flavor, Size } from "../types/common.js";
import { TyComponent } from "../base/ty-component.js";
import type { PropertyChange } from "../utils/property-manager.js";
import { ensureStyles } from "../utils/styles.js";
import { syncCustomFlavorSheet } from "../utils/flavor-sheet.js";
import { checkboxStyles, checkboxCustomFlavorCss } from "../styles/checkbox.js";

/**
 * Component internal state (for typing TyComponent)
 */
interface CheckboxState {
  checked: boolean;
  listenersSetup: boolean;
}

/**
 * Checkmark icon (Lucide `check`, same glyph as ty-option's selected check;
 * stroke-width 3 for presence at 16px — it replaces a heavy fill glyph).
 * Same glyph for checked and unchecked — checked shows it at full color,
 * unchecked at faint color (see styles).
 */
const CHECK_ICON = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6 9 17l-5-5"/></svg>`;

/**
 * Dash icon (Lucide `minus`) — shown while indeterminate.
 */
const DASH_ICON = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/></svg>`;

/**
 * TyCheckbox Element Interface
 */
export interface TyCheckboxElement extends HTMLElement {
  checked: boolean;
  indeterminate: boolean;
  value: string;
  name: string;
  disabled: boolean;
  required: boolean;
  size: Size;
  flavor: Flavor;
  form: HTMLFormElement | null;
}

/**
 * Ty Checkbox Component
 */
export class TyCheckbox
  extends TyComponent<CheckboxState>
  implements TyCheckboxElement
{
  static formAssociated = true;

  protected static properties = {
    checked: {
      type: "boolean" as const,
      visual: true,
      formValue: true,
      emitChange: true,
      default: false,
    },
    // Visual/ARIA "mixed" state (native semantics: no form-value effect,
    // clicking resolves to checked)
    indeterminate: {
      type: "boolean" as const,
      visual: true,
      default: false,
    },
    // Form submission value (when checked)
    value: {
      type: "string" as const,
      default: "on",
    },
    name: {
      type: "string" as const,
      default: "",
    },
    disabled: {
      type: "boolean" as const,
      visual: true,
      default: false,
    },
    required: {
      type: "boolean" as const,
      visual: true,
      default: false,
    },
    size: {
      type: "string" as const,
      visual: true,
      default: "md",
      validate: (v: any) => ["xs", "sm", "md", "lg", "xl"].includes(v),
      coerce: (v: any) => {
        if (!["xs", "sm", "md", "lg", "xl"].includes(v)) {
          console.warn(`[ty-checkbox] Invalid size '${v}'. Using 'md'.`);
          return "md";
        }
        return v;
      },
    },
    // Any string is accepted: built-ins get static CSS, other identifiers
    // become custom flavors (see _syncCustomFlavor), garbage degrades to
    // the default look.
    flavor: {
      type: "string" as const,
      visual: true,
      default: "neutral",
    },
  };

  // Internal state, not managed by PropertyManager
  // (_internals is provided by the TyComponent base class)
  private _customFlavorSheet: CSSStyleSheet | null = null;
  private _listenersSetup: boolean = false;

  // Store references to handlers for cleanup
  private _clickHandler: ((e: Event) => void) | null = null;
  private _keydownHandler: ((e: Event) => void) | null = null;
  private _focusHandler: (() => void) | null = null;
  private _blurHandler: (() => void) | null = null;

  constructor() {
    super(); // TyComponent handles attachInternals() and attachShadow()

    const shadow = this.shadowRoot!;
    ensureStyles(shadow, { css: checkboxStyles, id: "ty-checkbox" });
  }

  // observedAttributes auto-generated by TyComponent from properties config

  /** TyComponent already handled pre-connection property capture. */
  protected onConnect(): void {
    // Re-arm listeners on RE-connect: the base class skips render() when
    // already rendered, and onDisconnect removed the listeners. No-ops on
    // first connect (no container yet — render() attaches them).
    this.setupEventListeners();
    this._syncCustomFlavor();
  }

  /** Custom (non-built-in) flavors — see utils/flavor-sheet.ts. */
  private _syncCustomFlavor(): void {
    this._customFlavorSheet = syncCustomFlavorSheet(
      this.shadowRoot!,
      this._customFlavorSheet,
      this.flavor,
      ({ base }) => checkboxCustomFlavorCss(base),
    );
  }

  protected onDisconnect(): void {
    this.removeEventListeners();
  }

  /**
   * Handle property changes - called BEFORE render
   */
  protected onPropertiesChanged(changes: PropertyChange[]): void {
    if (changes.some((c) => c.name === "flavor")) {
      this._syncCustomFlavor();
    }
  }

  /**
   * Override form value to return value when checked, null when unchecked
   */
  protected getFormValue(): FormDataEntryValue | null {
    return this.checked ? this.value : null;
  }

  private buildClassList(): string {
    const classes: string[] = [this.size];

    if (this.disabled) classes.push("disabled");
    if (this.required) classes.push("required");

    return classes.join(" ");
  }

  private handleCheckboxClick(e: Event): void {
    if (this.disabled) return;
    if (this.isDuplicateActivationClick()) return;

    // Native semantics: clicking an indeterminate checkbox resolves to checked
    const newValue = this.indeterminate ? true : !this.checked;
    if (this.indeterminate) this.indeterminate = false;
    this.checked = newValue;

    // Emit custom events after property update
    setTimeout(() => {
      const eventDetail = {
        value: newValue,
        checked: newValue,
        formValue: newValue ? this.value : null,
        originalEvent: e,
      };

      this.dispatchEvent(
        new CustomEvent("input", {
          detail: eventDetail,
          bubbles: true,
          composed: true,
        }),
      );

      this.dispatchEvent(
        new CustomEvent("change", {
          detail: eventDetail,
          bubbles: true,
          composed: true,
        }),
      );
    }, 0);
  }

  private handleCheckboxKeydown(e: KeyboardEvent): void {
    if (this.disabled) return;

    if (["Space", " ", "Enter"].includes(e.key)) {
      e.preventDefault(); // Prevent default for keyboard to avoid page scroll
      e.stopPropagation();
      this.handleCheckboxClick(e);
    }
  }

  private removeEventListeners(): void {
    if (!this._listenersSetup) return;

    // Click lives on the HOST (label delegation + full-element trigger) —
    // remove it before the shadow-container guard below.
    if (this._clickHandler) {
      this.removeEventListener("click", this._clickHandler);
      this._clickHandler = null;
    }

    const shadow = this.shadowRoot;
    if (!shadow) return;

    const checkboxEl = shadow.querySelector(".checkbox-container");
    if (!checkboxEl) {
      this._listenersSetup = false;
      return;
    }

    if (this._keydownHandler) {
      checkboxEl.removeEventListener("keydown", this._keydownHandler);
      this._keydownHandler = null;
    }

    if (this._focusHandler) {
      checkboxEl.removeEventListener("focus", this._focusHandler);
      this._focusHandler = null;
    }

    if (this._blurHandler) {
      checkboxEl.removeEventListener("blur", this._blurHandler);
      this._blurHandler = null;
    }

    this._listenersSetup = false;
  }

  /**
   * Setup event listeners for checkbox functionality
   * IMPORTANT: Only called ONCE, not on every render
   */
  private setupEventListeners(): void {
    if (this._listenersSetup) return;

    const shadow = this.shadowRoot!;
    const checkboxEl = shadow.querySelector(".checkbox-container");

    if (!checkboxEl) return;

    // Create and store handler references for cleanup
    this._clickHandler = (e: Event) => {
      this.handleCheckboxClick(e);
    };

    this._keydownHandler = (e: Event) => {
      this.handleCheckboxKeydown(e as KeyboardEvent);
    };

    this._focusHandler = () => {
      checkboxEl.classList.add("focused");
    };

    this._blurHandler = () => {
      checkboxEl.classList.remove("focused");
    };

    // Click on the HOST: makes the whole element a trigger and lets a wrapping
    // <label> delegate (the synthetic click lands on the host, not the shadow).
    // Keyboard/focus stay on the focusable container.
    this.addEventListener("click", this._clickHandler);
    checkboxEl.addEventListener("keydown", this._keydownHandler);
    checkboxEl.addEventListener("focus", this._focusHandler);
    checkboxEl.addEventListener("blur", this._blurHandler);

    this._listenersSetup = true;
  }

  /**
   * Render the checkbox — just the box visual.
   * Label, required asterisk, and error UI are the consumer's responsibility.
   */
  protected render(): void {
    const shadow = this.shadowRoot!;
    let checkboxEl = shadow.querySelector(".checkbox-container") as HTMLElement;
    const classes = this.buildClassList();
    const ariaChecked = this.indeterminate ? "mixed" : String(this.checked);

    if (!checkboxEl) {
      checkboxEl = document.createElement("div");
      checkboxEl.className = "checkbox-container " + classes;
      checkboxEl.tabIndex = this.disabled ? -1 : 0;
      checkboxEl.setAttribute("role", "checkbox");
      checkboxEl.setAttribute("aria-checked", ariaChecked);
      checkboxEl.setAttribute("aria-disabled", String(this.disabled));
      checkboxEl.setAttribute("aria-required", String(this.required));

      const checkboxIcon = document.createElement("div");
      checkboxIcon.className = "checkbox-icon";
      checkboxEl.appendChild(checkboxIcon);

      shadow.appendChild(checkboxEl);
    } else {
      checkboxEl.className = "checkbox-container " + classes;
      checkboxEl.tabIndex = this.disabled ? -1 : 0;
      checkboxEl.setAttribute("aria-checked", ariaChecked);
      checkboxEl.setAttribute("aria-disabled", String(this.disabled));
      checkboxEl.setAttribute("aria-required", String(this.required));
    }

    // Dash while indeterminate, tick otherwise (tick's color/opacity carries
    // the checked/unchecked distinction via CSS).
    const icon = checkboxEl.querySelector(".checkbox-icon")!;
    icon.innerHTML = this.indeterminate ? DASH_ICON : CHECK_ICON;

    // (Re)attach listeners — onDisconnect removes them, so a reconnected
    // element needs them again even though the container already exists.
    this.setupEventListeners();

    // a11y: role="checkbox" lives on this inner element, but the associated
    // <label> names the (form-associated) host. Mirror that name onto the role
    // element so it has an accessible name.
    this.applyLabelName(checkboxEl);

    // Reflect constraint validation to the owning <form> (required was cosmetic).
    this.updateValidity();
  }

  /** required + unchecked => valueMissing; otherwise valid. */
  private updateValidity(): void {
    const anchor = this.shadowRoot?.querySelector(".checkbox-container") as HTMLElement | null;
    if (this.disabled) { this._internals.setValidity({}); return; }
    if (this.required && !this.checked) {
      this._internals.setValidity({ valueMissing: true }, "Please check this box", anchor ?? undefined);
    } else {
      this._internals.setValidity({});
    }
  }

  get checked(): boolean {
    return this.getProperty("checked");
  }

  set checked(value: boolean) {
    this.setProperty("checked", value);
  }

  get indeterminate(): boolean {
    return this.getProperty("indeterminate");
  }

  set indeterminate(value: boolean) {
    this.setProperty("indeterminate", value);
  }

  get value(): string {
    return this.getProperty("value");
  }

  set value(val: string) {
    this.setProperty("value", val);
  }

  get name(): string {
    return this.getProperty("name");
  }

  set name(val: string) {
    this.setProperty("name", val);
  }

  get disabled(): boolean {
    return this.getProperty("disabled");
  }

  set disabled(value: boolean) {
    this.setProperty("disabled", value);
  }

  get required(): boolean {
    return this.getProperty("required");
  }

  set required(value: boolean) {
    this.setProperty("required", value);
  }

  get size(): Size {
    return this.getProperty("size") as Size;
  }

  set size(value: Size) {
    this.setProperty("size", value);
  }

  get flavor(): Flavor {
    return this.getProperty("flavor") as Flavor;
  }

  set flavor(value: Flavor) {
    this.setProperty("flavor", value);
  }

  get form(): HTMLFormElement | null {
    return this._internals.form;
  }
}

if (!customElements.get("ty-checkbox")) {
  customElements.define("ty-checkbox", TyCheckbox);
}

