/**
 * TyIcon Web Component
 * PORTED FROM: clj/ty/components/icon.cljs
 * SVG icon component with size variants and animations
 */

import type { IconSize, IconTempo, TyIconElement } from '../types/common.js'
import { TyComponent } from '../base/ty-component.js'
import type { PropertyChange } from '../utils/property-manager.js'
import { ensureStyles } from '../utils/styles.js'
import { iconStyles } from '../styles/icon.js'
import * as IconRegistry from '../utils/icon-registry.js'

let _iconIdCounter = 0

/** Fallback SVG for missing icons - More visible to prevent layout shift */
const NOT_FOUND_ICON = `<svg xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 512 512"
      fill="currentColor"
      opacity="0.2">
   <path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512z"/>
</svg>`

/**
 * Component internal state (for typing TyComponent)
 */
interface IconState {
  name: string
  size: string
  spin: boolean
  pulse: boolean
  tempo: string
}

/**
 * Ty Icon Component
 *
 * @example
 * ```html
 * <ty-icon name="check"></ty-icon>
 * <ty-icon name="spinner" spin></ty-icon>
 * <ty-icon name="heart" size="xl"></ty-icon>
 * ```
 */
export class TyIcon extends TyComponent<IconState> implements TyIconElement {
  static formAssociated = false

  // ============================================================================
  // PROPERTY CONFIGURATION - Declarative property lifecycle
  // ============================================================================
  protected static properties = {
    name: { type: 'string' as const, visual: true, default: '' },
    size: { type: 'string' as const, visual: true, default: '' },
    spin: { type: 'boolean' as const, visual: true, default: false },
    pulse: { type: 'boolean' as const, visual: true, default: false },
    tempo: { type: 'string' as const, visual: true, default: '' },
  }

  // ============================================================================
  // INTERNAL STATE - Not managed by PropertyManager
  // ============================================================================

  private _watchId: string | null = null

  /** Track currently rendered SVG to avoid unnecessary re-renders */
  private _currentSvg: string = ''

  /**
   * Single shadow-DOM <slot> that holds either:
   *   - light-DOM children supplied by the user (server-side path: pasted SVG), or
   *   - fallback content driven by the registry (`name=`) or NOT_FOUND_ICON.
   *
   * Browser slot semantics handle precedence: when the host has assigned nodes,
   * the slot's fallback content is hidden automatically — no detection logic needed.
   */
  private _slot: HTMLSlotElement | null = null

  constructor() {
    super() // TyComponent handles attachInternals() and attachShadow()

    // Apply styles to shadow root
    ensureStyles(this.shadowRoot!, { css: iconStyles, id: 'ty-icon' })

    // Build the slot once. Fallback content shows when no light-DOM children are slotted.
    this._slot = document.createElement('slot')
    this._slot.innerHTML = NOT_FOUND_ICON
    this._currentSvg = NOT_FOUND_ICON
    this.shadowRoot!.appendChild(this._slot)
  }

  // observedAttributes auto-generated by TyComponent from properties config

  // ============================================================================
  // TYCOMPONENT LIFECYCLE HOOKS
  // ============================================================================

  /**
   * Called when component connects to DOM
   */
  protected onConnect(): void {
    // Generate unique watch ID
    this._watchId = `ty-icon-${++_iconIdCounter}`

    // Watch for registry changes that affect this icon
    if (this.name) {
      IconRegistry.addWatcher(this._watchId, this.name, (changedIcons) => {
        // Re-render if our icon changed
        if (this.name && changedIcons.has(this.name)) {
          this.render()
        }
      })
    }

    // Update host element classes
    this.updateClasses()

    // TyComponent will call render() automatically after this hook
  }

  /**
   * Called when component disconnects from DOM
   */
  protected onDisconnect(): void {
    // Clean up watcher
    if (this._watchId) {
      IconRegistry.removeWatcher(this._watchId)
      this._watchId = null
    }
  }

  /**
   * Handle property changes - called BEFORE render
   * Detects name changes to update icon registry watcher
   */
  protected onPropertiesChanged(changes: PropertyChange[]): void {
    for (const change of changes) {
      if (change.name === 'name') {
        // Remove old watcher
        if (this._watchId) {
          IconRegistry.removeWatcher(this._watchId)
        }

        // Re-add watcher for new name
        const newName = change.newValue || ''
        if (newName && this.isConnected) {
          this._watchId = `ty-icon-${++_iconIdCounter}`
          IconRegistry.addWatcher(this._watchId, newName, (changedIcons) => {
            if (this.name && changedIcons.has(this.name)) {
              this.render()
            }
          })
        }
      }
    }

    // Update host element classes for any visual change
    this.updateClasses()
  }

  // ============================================================================
  // PROPERTY ACCESSORS - Simple wrappers (no logic!)
  // ============================================================================

  get name(): string {
    return this.getProperty('name')
  }

  set name(value: string) {
    this.setProperty('name', value)
  }

  get size(): IconSize | undefined {
    const val = this.getProperty('size')
    return val || undefined
  }

  set size(value: IconSize | undefined) {
    this.setProperty('size', value || '')
  }

  get spin(): boolean {
    return this.getProperty('spin')
  }

  set spin(value: boolean) {
    this.setProperty('spin', value)
  }

  get pulse(): boolean {
    return this.getProperty('pulse')
  }

  set pulse(value: boolean) {
    this.setProperty('pulse', value)
  }

  get tempo(): IconTempo | undefined {
    const val = this.getProperty('tempo')
    return val || undefined
  }

  set tempo(value: IconTempo | undefined) {
    this.setProperty('tempo', value || '')
  }

  // ============================================================================
  // RENDERING
  // ============================================================================

  /** Build CSS classes for the host element */
  private buildClasses(): string[] {
    const classes: string[] = []

    // Size class
    const size = this.getProperty('size')
    if (size) {
      classes.push(`icon-${size}`)
    }

    // Animation classes
    if (this.getProperty('spin')) {
      classes.push('icon-spin')
    }

    if (this.getProperty('pulse')) {
      classes.push('icon-pulse')
    }

    // Tempo class
    const tempo = this.getProperty('tempo')
    if (tempo && (this.getProperty('spin') || this.getProperty('pulse'))) {
      classes.push(`icon-tempo-${tempo}`)
    }

    // Preserve user-added classes that don't conflict
    const currentClasses = this.className.split(/\s+/).filter(cls => {
      // Filter out component-managed classes
      return cls &&
        !cls.startsWith('icon-') &&
        cls !== 'icon-spin' &&
        cls !== 'icon-pulse'
    })

    return [...classes, ...currentClasses]
  }

  /** Update host element classes */
  private updateClasses(): void {
    const newClasses = this.buildClasses().join(' ')
    if (this.className !== newClasses) {
      this.className = newClasses
    }
  }

  /**
   * Render the icon SVG
   * Smart rendering strategy:
   * 1. Check memory registry (instant)
   * 2. If found in memory -> render immediately
   * 3. If not in memory -> show NOT_FOUND_ICON immediately (prevents empty state)
   * 4. Then check cache asynchronously and replace if found
   * 5. Only re-render if SVG actually changed
   */
  protected render(): void {
    const name = this.getProperty('name')

    if (!name) {
      this.renderSvg(NOT_FOUND_ICON)
      return
    }

    // Fast path: Check memory registry first
    const memorySvg = IconRegistry.getIcon(name)
    if (memorySvg) {
      this.renderSvg(memorySvg)
      return
    }

    this.renderSvg(NOT_FOUND_ICON)
  }

  /**
   * Update the slot's fallback content.
   * If the user has slotted light-DOM children (e.g., raw <svg>), the browser
   * shows those instead and the fallback stays hidden — but we still keep it
   * up to date so removing the children reveals the right registry/fallback SVG.
   */
  private renderSvg(svg: string): void {
    // Only render if content actually changed
    if (this._currentSvg === svg) {
      return
    }

    if (this._slot) {
      this._slot.innerHTML = svg
      this._currentSvg = svg
    }
  }
}

// Register the custom element
if (!customElements.get('ty-icon')) {
  customElements.define('ty-icon', TyIcon)
}

// Export for use in other modules
export { IconRegistry }
