/**
 * TyTag Web Component
 * PORTED FROM: clj/ty/components/tag.cljs
 * Tag component with slots and semantic flavors
 */

import type {
  Flavor,
  Size,
  TyTagElement,
  TyTagEventDetail,
} from "../types/common.js";
import { TyComponent } from "../base/ty-component.js";
import type { PropertyChange } from "../utils/property-manager.js";
import { ensureStyles } from "../utils/styles.js";
import { tagStyles } from "../styles/tag.js";

/**
 * Component internal state (for typing TyComponent)
 */
interface TagState {
  flavor: Flavor;
  size: Size;
  value: string;
  selected: boolean;
  pill: boolean;
  clickable: boolean;
  dismissible: boolean;
  disabled: boolean;
}

/**
 * Ty Tag Component
 *
 * @example
 * ```html
 * <ty-tag flavor="primary">Primary Tag</ty-tag>
 * <ty-tag flavor="success" dismissible>Success Tag</ty-tag>
 * <ty-tag flavor="danger" clickable>Clickable Tag</ty-tag>
 * <ty-tag value="tag-1" selected>Selected Tag</ty-tag>
 * ```
 */
export class TyTag extends TyComponent<TagState> implements TyTagElement {
  static formAssociated = true;

  // ============================================================================
  // PROPERTY CONFIGURATION - Declarative property lifecycle
  // ============================================================================
  protected static properties = {
    flavor: {
      type: "string" as const,
      visual: true,
      default: "neutral",
      // Built-in: primary | secondary | success | danger | warning | neutral.
      // Append `+` for stronger or `-` for softer shade (e.g. "primary+",
      // "danger-"). Any other string is passed through — theme custom flavors
      // via :host([flavor="X"]) { --tag-bg: ...; --tag-color: ...; --tag-border-color: ...; }
    },
    size: {
      type: "string" as const,
      visual: true,
      default: "md",
      validate: (v: any) => ["xs", "sm", "md", "lg", "xl"].includes(v),
      coerce: (v: any) => {
        if (!["xs", "sm", "md", "lg", "xl"].includes(v)) {
          console.warn(`[ty-tag] Invalid size '${v}'. Using 'md'.`);
          return "md";
        }
        return v;
      },
    },
    value: {
      type: "string" as const,
      visual: true,
      default: "",
    },
    selected: {
      type: "boolean" as const,
      visual: true,
      default: false,
    },
    pill: {
      type: "boolean" as const,
      visual: true,
      default: true,
      aliases: { "not-pill": false },
    },
    clickable: {
      type: "boolean" as const,
      visual: true,
      default: false,
    },
    dismissible: {
      type: "boolean" as const,
      visual: true,
      default: false,
    },
    disabled: {
      type: "boolean" as const,
      visual: true,
      default: false,
    },
  };

  // ============================================================================
  // INTERNAL STATE
  // ============================================================================

  // Event listener cleanup function
  private _cleanup: (() => void) | null = null;

  constructor() {
    super(); // TyComponent handles attachInternals() and attachShadow()

    // Apply styles to shadow root
    ensureStyles(this.shadowRoot!, { css: tagStyles, id: "ty-tag" });
  }

  // observedAttributes auto-generated by TyComponent from properties config

  // ============================================================================
  // TYCOMPONENT LIFECYCLE HOOKS
  // ============================================================================

  /**
   * Called when component connects to DOM
   * TyComponent already handled pre-connection property capture
   * TyComponent will call render() automatically after this hook
   */
  protected onConnect(): void {
    // Setup event listeners after initial render happens
    // Use queueMicrotask to ensure render() has been called by TyComponent
    queueMicrotask(() => {
      this.setupEventListeners();
    });
  }

  /**
   * Called when component disconnects from DOM
   */
  protected onDisconnect(): void {
    this.cleanupEventListeners();
  }

  /**
   * Handle property changes - called BEFORE render
   */
  protected onPropertiesChanged(_changes: PropertyChange[]): void {
    // No special handling needed - TyComponent handles rendering automatically
  }

  // ============================================================================
  // EVENT HANDLERS (arrow functions for stable references)
  // ============================================================================

  /**
   * Handle tag click events
   */
  private handleClick = (event: Event): void => {
    if (this.clickable && !this.disabled) {
      event.preventDefault();
      event.stopPropagation();
      this.dispatchTagEvent("click", { target: this });
      this.dispatchTagEvent("pointerdown", { target: this });
    }
  };

  /**
   * Handle tag dismiss events
   */
  private handleDismiss = (event: Event): void => {
    if (this.dismissible && !this.disabled) {
      event.preventDefault();
      event.stopPropagation();
      this.dispatchTagEvent("dismiss", { target: this });
    }
  };

  /**
   * Handle keyboard interactions
   */
  private handleKeydown = (event: Event): void => {
    const keyboardEvent = event as KeyboardEvent;
    if (this.disabled) return;

    const keyCode = keyboardEvent.keyCode;

    switch (keyCode) {
      // ENTER or SPACE - trigger click if clickable
      case 13: // Enter
      case 32: // Space
        if (this.clickable) {
          keyboardEvent.preventDefault();
          this.dispatchTagEvent("click", { target: this });
        }
        break;

      // DELETE or BACKSPACE - trigger dismiss if dismissible
      case 8: // Backspace
      case 46: // Delete
        if (this.dismissible) {
          keyboardEvent.preventDefault();
          this.dispatchTagEvent("dismiss", { target: this });
        }
        break;
    }
  };

  // ============================================================================
  // EVENT HELPERS
  // ============================================================================

  /**
   * Dispatch custom tag events
   */
  private dispatchTagEvent(eventType: string, detail: TyTagEventDetail): void {
    this.dispatchEvent(
      new CustomEvent(eventType, {
        detail,
        bubbles: true,
        composed: true,
        cancelable: true,
      }),
    );
  }

  /**
   * Clean up existing event listeners
   */
  private cleanupEventListeners(): void {
    if (this._cleanup) {
      this._cleanup();
      this._cleanup = null;
    }
  }

  /**
   * Setup event listeners for tag interactions
   */
  private setupEventListeners(): void {
    // Clean up any existing listeners first
    this.cleanupEventListeners();

    const shadow = this.shadowRoot!;
    const container = shadow.querySelector(".tag-container");
    const dismissBtn = shadow.querySelector(".tag-dismiss");

    if (!container) return;

    // Click handler for main tag
    container.addEventListener("click", this.handleClick);
    container.addEventListener("keydown", this.handleKeydown);

    // Dismiss button handler
    if (dismissBtn) {
      dismissBtn.addEventListener("click", this.handleDismiss);
    }

    // Store cleanup function
    this._cleanup = () => {
      container.removeEventListener("click", this.handleClick);
      container.removeEventListener("keydown", this.handleKeydown);
      if (dismissBtn) {
        dismissBtn.removeEventListener("click", this.handleDismiss);
      }
    };
  }

  // ============================================================================
  // RENDER
  // ============================================================================

  /**
   * Render the tag component
   */
  protected render(): void {
    const shadow = this.shadowRoot!;

    // Build the tag container
    const tabindex = this.clickable ? ' tabindex="0"' : "";
    const ariaDisabled = this.disabled ? ' aria-disabled="true"' : "";
    const dataValue = this.value ? ` data-value="${this.value}"` : "";

    // Build dismiss button SVG
    const dismissButton = this.dismissible
      ? `
      <button class="tag-dismiss" type="button" aria-label="Remove tag">
        <svg viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
        </svg>
      </button>
    `
      : "";

    shadow.innerHTML = `
      <div class="tag-container" part="container"${tabindex}${ariaDisabled}${dataValue}>
        <div class="tag-start">
          <slot name="start" class="tag-start"></slot>
        </div>
        <div class="tag-content">
          <slot></slot>
        </div>
        <div class="tag-end">
          <slot name="end"></slot>
          ${dismissButton}
        </div>
      </div>
    `;

    // Re-setup event listeners after innerHTML replace (destroys old elements)
    if (this._connected) {
      this.setupEventListeners();
    }
  }

  // ============================================================================
  // PROPERTY ACCESSORS - Simple wrappers (no logic!)
  // ============================================================================

  get flavor(): Flavor {
    return this.getProperty("flavor");
  }

  set flavor(value: Flavor) {
    this.setProperty("flavor", value);
  }

  get size(): Size {
    return this.getProperty("size") as Size;
  }

  set size(value: Size) {
    this.setProperty("size", value);
  }

  get value(): string {
    return this.getProperty("value");
  }

  set value(val: string) {
    this.setProperty("value", val);
  }

  get selected(): boolean {
    return this.getProperty("selected");
  }

  set selected(value: boolean) {
    this.setProperty("selected", value);
  }

  get pill(): boolean {
    return this.getProperty("pill");
  }

  set pill(value: boolean) {
    this.setProperty("pill", value);
  }

  get clickable(): boolean {
    return this.getProperty("clickable");
  }

  set clickable(value: boolean) {
    this.setProperty("clickable", value);
  }

  get dismissible(): boolean {
    return this.getProperty("dismissible");
  }

  set dismissible(value: boolean) {
    this.setProperty("dismissible", value);
  }

  get disabled(): boolean {
    return this.getProperty("disabled");
  }

  set disabled(value: boolean) {
    this.setProperty("disabled", value);
  }
}

// Register the custom element
if (!customElements.get("ty-tag")) {
  customElements.define("ty-tag", TyTag);
}
